version: '3.3'
services:
    db:
      build:
        context: ./Docker
        dockerfile: db.Dockerfile
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Trommelhelden1
      ports:
        - '1433:1433'
