<template>
  <div>
    <DataTable
      :value="customers"
      selectionMode="single"
      :paginator="true"
      :rowHover="true"
      isLoading="isLoading"
      class="p-datatable-sm"
      @page="onPage($event)"
      @sort="onSort($event)"
      @filter="onFilter($event)"
      :lazy="true"
      :rows="rows"
      :totalRecords="customers ? customers.length : 0"
      filterDisplay="menu"
      @rowSelect="onProductSelect"
      showGridlines
      currentPageReportTemplate="Showing {first} to {last} of {totalRecords}"
      :rowsPerPageOptions="[5, 10, 20, 50]"
      v-model:filters="filters"
      responsiveLayout="scroll"
    >
      <Column
        v-for="cols in columns"
        :field="cols.field"
        :header="cols.header"
        :showAddButton="false"
        :showFilterOperator="false"
        :dataType="cols.type"
        sortable
        ><template #filter="{ filterModel }">
          <InputText
            v-if="cols.type === 'text'"
            v-model="filterModel.value"
            class="p-column-filter"
            :placeholder="`Search by ${cols.header}`"
          />
          <InputNumber
            v-model="filterModel.value"
            class="p-column-filter"
            :useGrouping="false"
            :format="false"
            :placeholder="`Search by ${cols.header}`"
            v-else
          ></InputNumber>
        </template>
      </Column>
    </DataTable>
  </div>
</template>
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { FilterMatchMode, FilterOperator } from "primevue/api";
import CustomerService from "@/services/Customers";
import { IKunde } from "@/types";

const customerService = new CustomerService();
const isLoading = ref(false);
const customers = ref<IKunde[]>();
const rows = ref(5);
const page = ref(0);
const sortOptions: any = ref({});
const filterOptions: any = ref({});

const emit = defineEmits(["selectRow"]);

const filters = ref({
  KunName: {
    operator: FilterOperator.AND,
    constraints: [{ matchMode: FilterMatchMode.CONTAINS, value: null }],
  },
  KunNr: {
    operator: FilterOperator.AND,
    constraints: [{ matchMode: FilterMatchMode.EQUALS, value: null }],
  },
  KunOrt: {
    operator: FilterOperator.AND,
    constraints: [{ matchMode: FilterMatchMode.CONTAINS, value: null }],
  },
  KunPLZ: {
    operator: FilterOperator.AND,
    constraints: [{ matchMode: FilterMatchMode.EQUALS, value: null }],
  },
  KunStrasse: {
    operator: FilterOperator.AND,
    constraints: [{ matchMode: FilterMatchMode.CONTAINS, value: null }],
  },
});

const columns = [
  {
    header: "Name",
    field: "KunName",
    type: "text",
  },
  {
    header: "Kunden Nr.",
    field: "KunNr",
    type: "numeric",
  },
  {
    header: "Ort",
    field: "KunOrt",
    type: "text",
  },
  {
    header: "Postleitzahl",
    field: "KunPLZ",
    type: "text",
  },
  {
    header: "Straße",
    field: "KunStrasse",
    type: "text",
  },
];

onMounted(async () => {
  customers.value = [
    {
      KunNr: 508,
      KunName: "Sandra Bier",
      KunOrt: "Dresden",
      KunPLZ: "01217",
      KunStrasse: "Rubensweg 11",
    },
    {
      KunNr: 1000,
      KunName: "Mengel",
      KunOrt: "Burkau",
      KunPLZ: "01906",
      KunStrasse: "Lewickistrasse 56",
    },
    {
      KunNr: 1001,
      KunName: "Nehls",
      KunOrt: "Heide",
      KunPLZ: "08340",
      KunStrasse: "An den Baechen 56",
    },
    {
      KunNr: 1002,
      KunName: "Scheu",
      KunOrt: "Radeberg, Sachsen",
      KunPLZ: "01454",
      KunStrasse: "Helgolandstrasse 158",
    },
    {
      KunNr: 1003,
      KunName: "Stehr",
      KunOrt: "Jesewitz",
      KunPLZ: "04838",
      KunStrasse: "Rathausplatz 159",
    },
    {
      KunNr: 1004,
      KunName: "Brust",
      KunOrt: "Johannstadt",
      KunPLZ: "01169",
      KunStrasse: "Margaretendamm 83",
    },
    {
      KunNr: 1005,
      KunName: "Blau",
      KunOrt: "Markkleeberg",
      KunPLZ: "04416",
      KunStrasse: "Blochmatt 133",
    },
    {
      KunNr: 1006,
      KunName: "Hirschfeld",
      KunOrt: "Crostwitz",
      KunPLZ: "01920",
      KunStrasse: "Bernerstrasse 225",
    },
    {
      KunNr: 1007,
      KunName: "Ihle",
      KunOrt: "Dorfhain",
      KunPLZ: "01738",
      KunStrasse: "Overbergstrasse 209",
    },
    {
      KunNr: 1008,
      KunName: "Alex",
      KunOrt: "Oschatz",
      KunPLZ: "04758",
      KunStrasse: "Soester Strasse 56",
    },
    {
      KunNr: 1009,
      KunName: "Kuntz",
      KunOrt: "Dresden",
      KunPLZ: "01309",
      KunStrasse: "Kleinhausweg 92",
    },
    {
      KunNr: 1010,
      KunName: "Trautwein",
      KunOrt: "Niederau bei Meissen",
      KunPLZ: "01689",
      KunStrasse: "Kanizsaiweg 163",
    },
    {
      KunNr: 1011,
      KunName: "Waibel",
      KunOrt: "Ockerwitz",
      KunPLZ: "01462",
      KunStrasse: "Im Wickengarten 59",
    },
    {
      KunNr: 1012,
      KunName: "Thielmann",
      KunOrt: "Nauwalde",
      KunPLZ: "01609",
      KunStrasse: "Am Bauernbusch 225",
    },
    {
      KunNr: 1013,
      KunName: "Weitz",
      KunOrt: "Joehstadt",
      KunPLZ: "09477",
      KunStrasse: "Hubertusstr. 117",
    },
    {
      KunNr: 1014,
      KunName: "Scheele",
      KunOrt: "Wenigossa",
      KunPLZ: "04643",
      KunStrasse: "Steinfeldtstrasse 64",
    },
    {
      KunNr: 1015,
      KunName: "Sorg",
      KunOrt: "Markersbach",
      KunPLZ: "08352",
      KunStrasse: "Rotdornweg 243",
    },
    {
      KunNr: 1016,
      KunName: "Klaas",
      KunOrt: "Mutzschen",
      KunPLZ: "04688",
      KunStrasse: "Gruener Wald 5",
    },
    {
      KunNr: 1017,
      KunName: "Philipps",
      KunOrt: "Diesbar-Seusslitz",
      KunPLZ: "01612",
      KunStrasse: "Richterstrasse 194",
    },
    {
      KunNr: 1018,
      KunName: "Kolodziej",
      KunOrt: "Bernsbach",
      KunPLZ: "08315",
      KunStrasse: "Suedring 153",
    },
    {
      KunNr: 1019,
      KunName: "Ketterer",
      KunOrt: "Bockelwitz",
      KunPLZ: "04703",
      KunStrasse: "Am Rittergut 9",
    },
    {
      KunNr: 1020,
      KunName: "Stief",
      KunOrt: "Struppen",
      KunPLZ: "01796",
      KunStrasse: "Rebenweg 67",
    },
    {
      KunNr: 1021,
      KunName: "Engl",
      KunOrt: "Nausslitz",
      KunPLZ: "01159",
      KunStrasse: "Hainbuchenweg 177",
    },
    {
      KunNr: 1022,
      KunName: "Renken",
      KunOrt: "Wilsdruff",
      KunPLZ: "01723",
      KunStrasse: "Seebauerstr. 207",
    },
    {
      KunNr: 1023,
      KunName: "Burg",
      KunOrt: "Waldsteinberg",
      KunPLZ: "04821",
      KunStrasse: "Mariannenstrasse 182",
    },
    {
      KunNr: 1024,
      KunName: "Russ",
      KunOrt: "Pennrich",
      KunPLZ: "01156",
      KunStrasse: "Moosleite 199",
    },
    {
      KunNr: 1025,
      KunName: "Blumenthal",
      KunOrt: "Remse bei Glauchau",
      KunPLZ: "08373",
      KunStrasse: "In den Biegen 179",
    },
    {
      KunNr: 1026,
      KunName: "Woelfle",
      KunOrt: "Kirschau",
      KunPLZ: "02681",
      KunStrasse: "Lenbachstrasse 226",
    },
    {
      KunNr: 1027,
      KunName: "Moellers",
      KunOrt: "Stetzsch",
      KunPLZ: "01097",
      KunStrasse: "Zur Bachwiese 145",
    },
    {
      KunNr: 1028,
      KunName: "Osswald",
      KunOrt: "Laussnitz",
      KunPLZ: "01936",
      KunStrasse: "Heidemuehlweg 6",
    },
    {
      KunNr: 1029,
      KunName: "Birkholz",
      KunOrt: "Kreischa bei Dresden",
      KunPLZ: "01731",
      KunStrasse: "Dorfplatz 29",
    },
    {
      KunNr: 1030,
      KunName: "Graetz",
      KunOrt: "Neukirchen / Pleisse",
      KunPLZ: "08459",
      KunStrasse: "Scheidstrasse 172",
    },
    {
      KunNr: 1031,
      KunName: "Bienert",
      KunOrt: "Battaune",
      KunPLZ: "04838",
      KunStrasse: "Am alten Bahnhof 112",
    },
    {
      KunNr: 1032,
      KunName: "Pichler",
      KunOrt: "Thuemmlitzwalde",
      KunPLZ: "04668",
      KunStrasse: "Ziegeleistrasse 83",
    },
    {
      KunNr: 1033,
      KunName: "Glass",
      KunOrt: "Glaubitz",
      KunPLZ: "01612",
      KunStrasse: "Rosentalweg 28",
    },
    {
      KunNr: 1034,
      KunName: "Neuner",
      KunOrt: "Kaendler",
      KunPLZ: "09247",
      KunStrasse: "Am Alten Bahndamm 35",
    },
    {
      KunNr: 1035,
      KunName: "Heinisch",
      KunOrt: "Neisseaue",
      KunPLZ: "02829",
      KunStrasse: "Zelenkastrasse 44",
    },
    {
      KunNr: 1036,
      KunName: "Gohlke",
      KunOrt: "Plauen, Vogtland",
      KunPLZ: "08527",
      KunStrasse: "Lerchenweg 147",
    },
    {
      KunNr: 1037,
      KunName: "Langhammer",
      KunOrt: "Steinpleis",
      KunPLZ: "08432",
      KunStrasse: "Suedhang 145",
    },
    {
      KunNr: 1038,
      KunName: "Sanders",
      KunOrt: "Leipzig",
      KunPLZ: "04229",
      KunStrasse: "Rebenweg 35",
    },
    {
      KunNr: 1039,
      KunName: "Baeumer",
      KunOrt: "Bad Schlema",
      KunPLZ: "08301",
      KunStrasse: "Neckarstrasse 160",
    },
    {
      KunNr: 1040,
      KunName: "Coenen",
      KunOrt: "Paschwitz",
      KunPLZ: "04838",
      KunStrasse: "Malergaesschen 241",
    },
    {
      KunNr: 1041,
      KunName: "Kuck",
      KunOrt: "Dresden",
      KunPLZ: "01237",
      KunStrasse: "Mainzer Strasse 224",
    },
    {
      KunNr: 1042,
      KunName: "Berens",
      KunOrt: "Delitzsch",
      KunPLZ: "04509",
      KunStrasse: "Boecklerstrasse 131",
    },
    {
      KunNr: 1043,
      KunName: "Dost",
      KunOrt: "Karcha",
      KunPLZ: "01683",
      KunStrasse: "Lepsiusstrasse 155",
    },
    {
      KunNr: 1044,
      KunName: "Heidt",
      KunOrt: "Waldsteinberg",
      KunPLZ: "04821",
      KunStrasse: "Feldstrasse 121",
    },
    {
      KunNr: 1045,
      KunName: "Fix",
      KunOrt: "Dennheritz",
      KunPLZ: "08393",
      KunStrasse: "Basaltstrasse 210",
    },
    {
      KunNr: 1046,
      KunName: "Marschner",
      KunOrt: "Weisskeissel",
      KunPLZ: "02957",
      KunStrasse: "Gaertnereistrasse 3",
    },
    {
      KunNr: 1047,
      KunName: "Haberkorn",
      KunOrt: "Karcha",
      KunPLZ: "01683",
      KunStrasse: "Repsoldstrasse 190",
    },
    {
      KunNr: 1048,
      KunName: "Redlich",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09111",
      KunStrasse: "Aspichring 5",
    },
    {
      KunNr: 1049,
      KunName: "Karle",
      KunOrt: "Raeckelwitz",
      KunPLZ: "01920",
      KunStrasse: "Jarrestrasse 55",
    },
    {
      KunNr: 1050,
      KunName: "Dippel",
      KunOrt: "Hainichen, Sachsen",
      KunPLZ: "09661",
      KunStrasse: "Neuburgstaedtel 142",
    },
    {
      KunNr: 1051,
      KunName: "Kloss",
      KunOrt: "Leubnitz bei Plauen",
      KunPLZ: "08412",
      KunStrasse: "Hoefnageleck 44",
    },
    {
      KunNr: 1052,
      KunName: "Blau",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "02633",
      KunStrasse: "Kapellenweg 72",
    },
    {
      KunNr: 1053,
      KunName: "Schwenke",
      KunOrt: "Gornau / Erzgebirge",
      KunPLZ: "09405",
      KunStrasse: "Oltersteinweg 5",
    },
    {
      KunNr: 1054,
      KunName: "Stoffel",
      KunOrt: "Kreissa",
      KunPLZ: "01623",
      KunStrasse: "Raehnitzsteig 135",
    },
    {
      KunNr: 1055,
      KunName: "Krausse",
      KunOrt: "Leipzig",
      KunPLZ: "04178",
      KunStrasse: "Am Ziegenberg 66",
    },
    {
      KunNr: 1056,
      KunName: "Lucht",
      KunOrt: "Rackwitz",
      KunPLZ: "04519",
      KunStrasse: "Elmtwiete 243",
    },
    {
      KunNr: 1057,
      KunName: "Gaida",
      KunOrt: "Gorbitz",
      KunPLZ: "01109",
      KunStrasse: "Mussstr. 78",
    },
    {
      KunNr: 1058,
      KunName: "Dehn",
      KunOrt: "Reuth bei Plauen",
      KunPLZ: "08538",
      KunStrasse: "Diakonissenweg 8",
    },
    {
      KunNr: 1059,
      KunName: "Gilles",
      KunOrt: "Oschatz",
      KunPLZ: "04758",
      KunStrasse: "Am Hirschknock 117",
    },
    {
      KunNr: 1060,
      KunName: "Schmoll",
      KunOrt: "Kubschuetz",
      KunPLZ: "02627",
      KunStrasse: "Gaertnerstrasse 229",
    },
    {
      KunNr: 1061,
      KunName: "Bendel",
      KunOrt: "Schlegel bei Zittau",
      KunPLZ: "02788",
      KunStrasse: "Emdener Strasse 72",
    },
    {
      KunNr: 1062,
      KunName: "Schwenke",
      KunOrt: "Floeha",
      KunPLZ: "09557",
      KunStrasse: "Hittenkoferweg 87",
    },
    {
      KunNr: 1063,
      KunName: "Hinkel",
      KunOrt: "Dresden",
      KunPLZ: "01279",
      KunStrasse: "Anwanderstr. 212",
    },
    {
      KunNr: 1064,
      KunName: "Daniels",
      KunOrt: "Zwickau",
      KunPLZ: "08060",
      KunStrasse: "Erzbergerstrasse 202",
    },
    {
      KunNr: 1065,
      KunName: "Lehnen",
      KunOrt: "Steinbach",
      KunPLZ: "01156",
      KunStrasse: "Zum Jammertal 98",
    },
    {
      KunNr: 1066,
      KunName: "Bernard",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09117",
      KunStrasse: "Moeringbogen 6",
    },
    {
      KunNr: 1067,
      KunName: "Kehr",
      KunOrt: "Gornau / Erzgebirge",
      KunPLZ: "09405",
      KunStrasse: "Am Foehrenwald 176",
    },
    {
      KunNr: 1068,
      KunName: "Kienzle",
      KunOrt: "Plattenthal",
      KunPLZ: "09488",
      KunStrasse: "Calvinstrasse 101",
    },
    {
      KunNr: 1069,
      KunName: "Coenen",
      KunOrt: "Thermalbad Wiesenbad",
      KunPLZ: "09488",
      KunStrasse: "Grimoldweg 111",
    },
    {
      KunNr: 1070,
      KunName: "Wolfrum",
      KunOrt: "Zschadrass",
      KunPLZ: "04680",
      KunStrasse: "Bitterfelder Weg 51",
    },
    {
      KunNr: 1071,
      KunName: "Sager",
      KunOrt: "Nausslitz",
      KunPLZ: "01189",
      KunStrasse: "Am Weissen Turm 48",
    },
    {
      KunNr: 1072,
      KunName: "Liese",
      KunOrt: "Wildenfels",
      KunPLZ: "08134",
      KunStrasse: "In der Suedflur 141",
    },
    {
      KunNr: 1073,
      KunName: "Dillmann",
      KunOrt: "Gorbitz",
      KunPLZ: "01129",
      KunStrasse: "Zum Stulen 85",
    },
    {
      KunNr: 1074,
      KunName: "Dudek",
      KunOrt: "Groeditz bei Riesa",
      KunPLZ: "01609",
      KunStrasse: "Albanusstrasse 77",
    },
    {
      KunNr: 1075,
      KunName: "Steinborn",
      KunOrt: "Muelsen",
      KunPLZ: "08132",
      KunStrasse: "Dresdner Strasse 179",
    },
    {
      KunNr: 1076,
      KunName: "Eichholz",
      KunOrt: "Demitz-Thumitz",
      KunPLZ: "01877",
      KunStrasse: "Dorfstrasse 43",
    },
    {
      KunNr: 1077,
      KunName: "Wilk",
      KunOrt: "Abend",
      KunPLZ: "01623",
      KunStrasse: "Diebsgrundweg 163",
    },
    {
      KunNr: 1078,
      KunName: "Lay",
      KunOrt: "Leisnig",
      KunPLZ: "04703",
      KunStrasse: "Im Burgfeld 180",
    },
    {
      KunNr: 1079,
      KunName: "Velten",
      KunOrt: "Thuemmlitzwalde",
      KunPLZ: "04668",
      KunStrasse: "Kirchenweg 34",
    },
    {
      KunNr: 1080,
      KunName: "Moench",
      KunOrt: "Johannstadt",
      KunPLZ: "01237",
      KunStrasse: "Torweg 39",
    },
    {
      KunNr: 1081,
      KunName: "Brix",
      KunOrt: "Nossen",
      KunPLZ: "01683",
      KunStrasse: "Heynahtsstrasse 147",
    },
    {
      KunNr: 1082,
      KunName: "Blumenthal",
      KunOrt: "Striesen-West",
      KunPLZ: "01307",
      KunStrasse: "Sandhoefer Allee 10",
    },
    {
      KunNr: 1083,
      KunName: "Edel",
      KunOrt: "Naunhof bei Grimma",
      KunPLZ: "04683",
      KunStrasse: "Rhiemsweg 69",
    },
    {
      KunNr: 1084,
      KunName: "Findeisen",
      KunOrt: "Sankt Micheln",
      KunPLZ: "08132",
      KunStrasse: "Ganghoferstrasse 38",
    },
    {
      KunNr: 1085,
      KunName: "Weidmann",
      KunOrt: "Johannstadt",
      KunPLZ: "01307",
      KunStrasse: "Laschoberstrasse 59",
    },
    {
      KunNr: 1086,
      KunName: "Moench",
      KunOrt: "Gorbitz",
      KunPLZ: "01156",
      KunStrasse: "Weegmannufer 91",
    },
    {
      KunNr: 1087,
      KunName: "Sacher",
      KunOrt: "Elstertrebnitz",
      KunPLZ: "04523",
      KunStrasse: "Londoner Strasse 12",
    },
    {
      KunNr: 1088,
      KunName: "Guse",
      KunOrt: "Eppendorf, Sachsen",
      KunPLZ: "09575",
      KunStrasse: "Boecklerstrasse 45",
    },
    {
      KunNr: 1089,
      KunName: "Vater",
      KunOrt: "Gorbitz",
      KunPLZ: "01307",
      KunStrasse: "Zum Tierheim 26",
    },
    {
      KunNr: 1090,
      KunName: "Theil",
      KunOrt: "Bad Dueben",
      KunPLZ: "04849",
      KunStrasse: "Falkenstrasse 58",
    },
    {
      KunNr: 1091,
      KunName: "Matthiesen",
      KunOrt: "Augustusburg",
      KunPLZ: "09573",
      KunStrasse: "Raabestrasse 40",
    },
    {
      KunNr: 1092,
      KunName: "Reber",
      KunOrt: "Muecka",
      KunPLZ: "02906",
      KunStrasse: "Niederschleems 148",
    },
    {
      KunNr: 1093,
      KunName: "Stoffel",
      KunOrt: "Weissenberg, Sachsen",
      KunPLZ: "02627",
      KunStrasse: "Wilhelmstrasse 174",
    },
    {
      KunNr: 1094,
      KunName: "Steinborn",
      KunOrt: "Nausslitz",
      KunPLZ: "01189",
      KunStrasse: "Tuchmachergasse 195",
    },
    {
      KunNr: 1095,
      KunName: "Geissler",
      KunOrt: "Zitzschen",
      KunPLZ: "04442",
      KunStrasse: "Eisgrubenweg 11",
    },
    {
      KunNr: 1096,
      KunName: "Seliger",
      KunOrt: "Bischofswerda",
      KunPLZ: "01877",
      KunStrasse: "Landgraben 19",
    },
    {
      KunNr: 1097,
      KunName: "Schoenberg",
      KunOrt: "Gruenhain",
      KunPLZ: "08358",
      KunStrasse: "Seewiesenstr. 96",
    },
    {
      KunNr: 1098,
      KunName: "Laumann",
      KunOrt: "Leipzig",
      KunPLZ: "04103",
      KunStrasse: "Hertelstrasse 56",
    },
    {
      KunNr: 1099,
      KunName: "Nehring",
      KunOrt: "Leipzig",
      KunPLZ: "04205",
      KunStrasse: "Buergerweide 86",
    },
    {
      KunNr: 1100,
      KunName: "Ender",
      KunOrt: "Dresden",
      KunPLZ: "01465",
      KunStrasse: "Faehrmannweg 132",
    },
    {
      KunNr: 1101,
      KunName: "Rist",
      KunOrt: "Stoermthal",
      KunPLZ: "04463",
      KunStrasse: "Fabrikbau 149",
    },
    {
      KunNr: 1102,
      KunName: "Weihrauch",
      KunOrt: "Deutschneudorf",
      KunPLZ: "09548",
      KunStrasse: "Am Talkenberg 66",
    },
    {
      KunNr: 1103,
      KunName: "Mildner",
      KunOrt: "Siebenlehn",
      KunPLZ: "09634",
      KunStrasse: "Kapstadtring 43",
    },
    {
      KunNr: 1104,
      KunName: "Mauch",
      KunOrt: "Malter",
      KunPLZ: "01744",
      KunStrasse: "Altraecknitz 12",
    },
    {
      KunNr: 1105,
      KunName: "Voelkl",
      KunOrt: "Striesen-Sued",
      KunPLZ: "01307",
      KunStrasse: "Luchbergstrasse 147",
    },
    {
      KunNr: 1106,
      KunName: "Scheu",
      KunOrt: "Dommitzsch",
      KunPLZ: "04880",
      KunStrasse: "Archivstrasse 212",
    },
    {
      KunNr: 1107,
      KunName: "Kapp",
      KunOrt: "Brandis bei Wurzen",
      KunPLZ: "04821",
      KunStrasse: "Dalbergstrasse 8",
    },
    {
      KunNr: 1108,
      KunName: "Streich",
      KunOrt: "Gorbitz",
      KunPLZ: "01169",
      KunStrasse: "Vierlinden 134",
    },
    {
      KunNr: 1109,
      KunName: "Coenen",
      KunOrt: "Gorbitz",
      KunPLZ: "01462",
      KunStrasse: "Buergerstrasse 10",
    },
    {
      KunNr: 1110,
      KunName: "Prange",
      KunOrt: "Ockerwitz",
      KunPLZ: "01462",
      KunStrasse: "Gerberstr. 113",
    },
    {
      KunNr: 1111,
      KunName: "Sieger",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "01877",
      KunStrasse: "Hirtenweg 138",
    },
    {
      KunNr: 1112,
      KunName: "Woehrle",
      KunOrt: "Leipzig",
      KunPLZ: "04347",
      KunStrasse: "Untere Sandstr. 118",
    },
    {
      KunNr: 1113,
      KunName: "Dudek",
      KunOrt: "Stannewisch",
      KunPLZ: "02923",
      KunStrasse: "Krugtwiete 25",
    },
    {
      KunNr: 1114,
      KunName: "Kaempf",
      KunOrt: "Bad Brambach",
      KunPLZ: "08648",
      KunStrasse: "An der Flutrinne 100",
    },
    {
      KunNr: 1115,
      KunName: "Krell",
      KunOrt: "Langenbernsdorf",
      KunPLZ: "08428",
      KunStrasse: "Bombaybruecke 9",
    },
    {
      KunNr: 1116,
      KunName: "Bensch",
      KunOrt: "Grossbothen",
      KunPLZ: "04668",
      KunStrasse: "Grubenweg 202",
    },
    {
      KunNr: 1117,
      KunName: "Stevens",
      KunOrt: "Doebeln",
      KunPLZ: "04720",
      KunStrasse: "Seeligstrasse 67",
    },
    {
      KunNr: 1118,
      KunName: "Giesecke",
      KunOrt: "Rossau bei Mittweida",
      KunPLZ: "09661",
      KunStrasse: "Am Kronenhuegel 71",
    },
    {
      KunNr: 1119,
      KunName: "Ruhl",
      KunOrt: "Steinpleis",
      KunPLZ: "08432",
      KunStrasse: "Bachforellenweg 186",
    },
    {
      KunNr: 1120,
      KunName: "Haberkorn",
      KunOrt: "Hohenstein-Ernstthal",
      KunPLZ: "09337",
      KunStrasse: "Jochhoeh 51",
    },
    {
      KunNr: 1121,
      KunName: "Szymanski",
      KunOrt: "Markranstaedt",
      KunPLZ: "04420",
      KunStrasse: "Tabulatorweg 118",
    },
    {
      KunNr: 1122,
      KunName: "Friedmann",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09120",
      KunStrasse: "Buger Hauptstr. 42",
    },
    {
      KunNr: 1123,
      KunName: "Koelsch",
      KunOrt: "Gorbitz",
      KunPLZ: "01097",
      KunStrasse: "Lugaer Strasse 151",
    },
    {
      KunNr: 1124,
      KunName: "Juenger",
      KunOrt: "Gorbitz",
      KunPLZ: "01307",
      KunStrasse: "Margeritenstrasse 10",
    },
    {
      KunNr: 1125,
      KunName: "Dannenberg",
      KunOrt: "Mildenau",
      KunPLZ: "09456",
      KunStrasse: "Londoner Strasse 86",
    },
    {
      KunNr: 1126,
      KunName: "Lex",
      KunOrt: "Stein",
      KunPLZ: "08118",
      KunStrasse: "Altkaditz 3",
    },
    {
      KunNr: 1127,
      KunName: "Kick",
      KunOrt: "Rietschen",
      KunPLZ: "02956",
      KunStrasse: "Ludwig-Gehm-Weg 57",
    },
    {
      KunNr: 1128,
      KunName: "Back",
      KunOrt: "Gorbitz",
      KunPLZ: "01127",
      KunStrasse: "Plattengasse 42",
    },
    {
      KunNr: 1129,
      KunName: "Wehrle",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "02633",
      KunStrasse: "Am Storchengrund 44",
    },
    {
      KunNr: 1130,
      KunName: "Fluegge",
      KunOrt: "Porschdorf",
      KunPLZ: "01814",
      KunStrasse: "Stengeletwiete 163",
    },
    {
      KunNr: 1131,
      KunName: "Huetter",
      KunOrt: "Leipzig",
      KunPLZ: "04109",
      KunStrasse: "Otto-Dix-Ring 209",
    },
    {
      KunNr: 1132,
      KunName: "Kehr",
      KunOrt: "Neuschoenburg",
      KunPLZ: "08132",
      KunStrasse: "Hoepers Kamp 70",
    },
    {
      KunNr: 1133,
      KunName: "Klinke",
      KunOrt: "Trebsen / Mulde",
      KunPLZ: "04687",
      KunStrasse: "Zelenkastrasse 137",
    },
    {
      KunNr: 1134,
      KunName: "Goerner",
      KunOrt: "Stein",
      KunPLZ: "08118",
      KunStrasse: "Boberger Strasse 90",
    },
    {
      KunNr: 1135,
      KunName: "Knoche",
      KunOrt: "Grossnaundorf",
      KunPLZ: "01936",
      KunStrasse: "Tullastrasse 105",
    },
    {
      KunNr: 1136,
      KunName: "Baumert",
      KunOrt: "Bahretal",
      KunPLZ: "01819",
      KunStrasse: "Sternplatz 133",
    },
    {
      KunNr: 1137,
      KunName: "Wedekind",
      KunOrt: "Wiedemar",
      KunPLZ: "04509",
      KunStrasse: "Karl-Gerold-Platz 34",
    },
    {
      KunNr: 1138,
      KunName: "Rump",
      KunOrt: "Johannstadt",
      KunPLZ: "01099",
      KunStrasse: "Kirchweg 213",
    },
    {
      KunNr: 1139,
      KunName: "Burg",
      KunOrt: "Nausslitz",
      KunPLZ: "01187",
      KunStrasse: "Hauptplatz 100",
    },
    {
      KunNr: 1140,
      KunName: "Freiberg",
      KunOrt: "Neumark, Sachsen",
      KunPLZ: "08496",
      KunStrasse: "Miquelallee 139",
    },
    {
      KunNr: 1141,
      KunName: "Dill",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09128",
      KunStrasse: "Neudecker Strasse 46",
    },
    {
      KunNr: 1142,
      KunName: "Schwenke",
      KunOrt: "Bautzen",
      KunPLZ: "02640",
      KunStrasse: "Eschenstrasse 98",
    },
    {
      KunNr: 1143,
      KunName: "Giebel",
      KunOrt: "Grossharthau",
      KunPLZ: "01909",
      KunStrasse: "Langobardenweg 87",
    },
    {
      KunNr: 1144,
      KunName: "Zettl",
      KunOrt: "Rosswein",
      KunPLZ: "04741",
      KunStrasse: "Teubnerweg 204",
    },
    {
      KunNr: 1145,
      KunName: "Diederichs",
      KunOrt: "Kirschau",
      KunPLZ: "02681",
      KunStrasse: "Bergesgrundweg 201",
    },
    {
      KunNr: 1146,
      KunName: "Theil",
      KunOrt: "Johannstadt",
      KunPLZ: "01307",
      KunStrasse: "Bulgakowstrasse 193",
    },
    {
      KunNr: 1147,
      KunName: "Bunge",
      KunOrt: "Striegistal",
      KunPLZ: "09661",
      KunStrasse: "Querweg 95",
    },
    {
      KunNr: 1148,
      KunName: "Trautwein",
      KunOrt: "Unkersdorf",
      KunPLZ: "01462",
      KunStrasse: "Tagetesweg 57",
    },
    {
      KunNr: 1149,
      KunName: "Waibel",
      KunOrt: "Doebernitz",
      KunPLZ: "04509",
      KunStrasse: "Burgenlandweg 208",
    },
    {
      KunNr: 1150,
      KunName: "Heintz",
      KunOrt: "Annaberg-Buchholz",
      KunPLZ: "09456",
      KunStrasse: "Heckenweg 18",
    },
    {
      KunNr: 1151,
      KunName: "Marschner",
      KunOrt: "Dresden",
      KunPLZ: "01326",
      KunStrasse: "Hofwiesenstrasse 219",
    },
    {
      KunNr: 1152,
      KunName: "Behrmann",
      KunOrt: "Leubnitz bei Plauen",
      KunPLZ: "08539",
      KunStrasse: "Weistropper Weg 99",
    },
    {
      KunNr: 1153,
      KunName: "Rosendahl",
      KunOrt: "Leipzig",
      KunPLZ: "04109",
      KunStrasse: "An der Foersterei 88",
    },
    {
      KunNr: 1154,
      KunName: "Kaemmerer",
      KunOrt: "Johannstadt",
      KunPLZ: "01109",
      KunStrasse: "Titusstr. 82",
    },
    {
      KunNr: 1155,
      KunName: "Schuele",
      KunOrt: "Annaberg-Buchholz",
      KunPLZ: "09456",
      KunStrasse: "Dantestrasse 232",
    },
    {
      KunNr: 1156,
      KunName: "Leonhard",
      KunOrt: "Neustadt in Sachsen",
      KunPLZ: "01844",
      KunStrasse: "Riedeck 209",
    },
    {
      KunNr: 1157,
      KunName: "Stueber",
      KunOrt: "Gorbitz-Sued",
      KunPLZ: "01169",
      KunStrasse: "Hummelweg 100",
    },
    {
      KunNr: 1158,
      KunName: "Wittek",
      KunOrt: "Gruna",
      KunPLZ: "01219",
      KunStrasse: "Schweizstrasse 197",
    },
    {
      KunNr: 1159,
      KunName: "Milz",
      KunOrt: "Neusalza-Spremberg",
      KunPLZ: "02742",
      KunStrasse: "Neudobritzer Weg 178",
    },
    {
      KunNr: 1160,
      KunName: "Patzer",
      KunOrt: "Zwickau",
      KunPLZ: "08064",
      KunStrasse: "Zimmerstrasse 25",
    },
    {
      KunNr: 1161,
      KunName: "Dettmann",
      KunOrt: "Markkleeberg",
      KunPLZ: "04416",
      KunStrasse: "Burkersdorfer Weg 48",
    },
    {
      KunNr: 1162,
      KunName: "Irmer",
      KunOrt: "Siebenlehn",
      KunPLZ: "09603",
      KunStrasse: "Edelhof 193",
    },
    {
      KunNr: 1163,
      KunName: "Steinle",
      KunOrt: "Neschwitz",
      KunPLZ: "02699",
      KunStrasse: "Josephinenstrasse 21",
    },
    {
      KunNr: 1164,
      KunName: "Jungbluth",
      KunOrt: "Striesen-West",
      KunPLZ: "01307",
      KunStrasse: "Altomsewitz 154",
    },
    {
      KunNr: 1165,
      KunName: "Brueckmann",
      KunOrt: "Dresden",
      KunPLZ: "01109",
      KunStrasse: "Max-Bromme-Steig 153",
    },
    {
      KunNr: 1166,
      KunName: "Meindl",
      KunOrt: "Arzberg bei Torgau",
      KunPLZ: "04886",
      KunStrasse: "Am Gaertchen 244",
    },
    {
      KunNr: 1167,
      KunName: "Jahns",
      KunOrt: "Lohsa",
      KunPLZ: "02999",
      KunStrasse: "Diebweg 185",
    },
    {
      KunNr: 1168,
      KunName: "Nadler",
      KunOrt: "Naunhof bei Grimma",
      KunPLZ: "04683",
      KunStrasse: "Brendelweg 166",
    },
    {
      KunNr: 1169,
      KunName: "Haecker",
      KunOrt: "Kaendler",
      KunPLZ: "09212",
      KunStrasse: "Bruehlsche Gasse 26",
    },
    {
      KunNr: 1170,
      KunName: "Bergemann",
      KunOrt: "Sankt Egidien",
      KunPLZ: "09356",
      KunStrasse: "Klauerstrasse 15",
    },
    {
      KunNr: 1171,
      KunName: "Schoeler",
      KunOrt: "Zschepplin",
      KunPLZ: "04838",
      KunStrasse: "Am Zschonergrund 143",
    },
    {
      KunNr: 1172,
      KunName: "Herter",
      KunOrt: "Elsterheide",
      KunPLZ: "02979",
      KunStrasse: "Trimbergstr. 44",
    },
    {
      KunNr: 1173,
      KunName: "Winzer",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "01877",
      KunStrasse: "Heidelbachstrasse 26",
    },
    {
      KunNr: 1174,
      KunName: "Bitzer",
      KunOrt: "Stetzsch",
      KunPLZ: "01279",
      KunStrasse: "Meinhardtweg 121",
    },
    {
      KunNr: 1175,
      KunName: "Dinter",
      KunOrt: "Oppach",
      KunPLZ: "02736",
      KunStrasse: "Stadthausbruecke 237",
    },
    {
      KunNr: 1176,
      KunName: "Hundt",
      KunOrt: "Zinna",
      KunPLZ: "04860",
      KunStrasse: "Intzestrasse 238",
    },
    {
      KunNr: 1177,
      KunName: "Senft",
      KunOrt: "Markneukirchen",
      KunPLZ: "08258",
      KunStrasse: "Herrnstrasse 50",
    },
    {
      KunNr: 1178,
      KunName: "Flick",
      KunOrt: "Gorbitz",
      KunPLZ: "01157",
      KunStrasse: "Ludwig-Fulda-Weg 126",
    },
    {
      KunNr: 1179,
      KunName: "Haberland",
      KunOrt: "Johannstadt",
      KunPLZ: "01099",
      KunStrasse: "Knorrstrasse 142",
    },
    {
      KunNr: 1180,
      KunName: "Nagler",
      KunOrt: "Plauen, Vogtland",
      KunPLZ: "08525",
      KunStrasse: "Bredowstrasse 198",
    },
    {
      KunNr: 1181,
      KunName: "Breunig",
      KunOrt: "Wehlen",
      KunPLZ: "01829",
      KunStrasse: "Affentorplatz 35",
    },
    {
      KunNr: 1182,
      KunName: "Osswald",
      KunOrt: "Neugersdorf, Sachsen",
      KunPLZ: "02727",
      KunStrasse: "Schadowstrasse 184",
    },
    {
      KunNr: 1183,
      KunName: "Bonk",
      KunOrt: "Gohrisch",
      KunPLZ: "01824",
      KunStrasse: "Altenburger Weg 244",
    },
    {
      KunNr: 1184,
      KunName: "Klostermann",
      KunOrt: "Johannstadt",
      KunPLZ: "01307",
      KunStrasse: "Langaugasse 205",
    },
    {
      KunNr: 1185,
      KunName: "Koellner",
      KunOrt: "Cotta",
      KunPLZ: "01157",
      KunStrasse: "Am Hafen 113",
    },
    {
      KunNr: 1186,
      KunName: "Hausner",
      KunOrt: "Oderwitz",
      KunPLZ: "02791",
      KunStrasse: "Hainweg 92",
    },
    {
      KunNr: 1187,
      KunName: "Heinig",
      KunOrt: "Roederaue",
      KunPLZ: "01609",
      KunStrasse: "Wunderburg 25",
    },
    {
      KunNr: 1188,
      KunName: "Bohlen",
      KunOrt: "Bischofswerda",
      KunPLZ: "01877",
      KunStrasse: "Gompitzer Hang 150",
    },
    {
      KunNr: 1189,
      KunName: "Koehne",
      KunOrt: "Bad Muskau",
      KunPLZ: "02953",
      KunStrasse: "Nachtigallenstieg 63",
    },
    {
      KunNr: 1190,
      KunName: "Kortmann",
      KunOrt: "Thierfeld",
      KunPLZ: "08118",
      KunStrasse: "An der Mainkur 162",
    },
    {
      KunNr: 1191,
      KunName: "Kamps",
      KunOrt: "Weinboehla",
      KunPLZ: "01689",
      KunStrasse: "Cottaweg 58",
    },
    {
      KunNr: 1192,
      KunName: "Thimm",
      KunOrt: "Crostau",
      KunPLZ: "02681",
      KunStrasse: "Wandalenweg 76",
    },
    {
      KunNr: 1193,
      KunName: "Nienhaus",
      KunOrt: "Johannstadt",
      KunPLZ: "01462",
      KunStrasse: "Derbyweg 147",
    },
    {
      KunNr: 1194,
      KunName: "Stach",
      KunOrt: "Kossa",
      KunPLZ: "04849",
      KunStrasse: "Hoetzlring 233",
    },
    {
      KunNr: 1195,
      KunName: "Thome",
      KunOrt: "Poehla, Erzgebirge",
      KunPLZ: "08352",
      KunStrasse: "Soltauer Chaussee 48",
    },
    {
      KunNr: 1196,
      KunName: "Stotz",
      KunOrt: "Johannstadt",
      KunPLZ: "01277",
      KunStrasse: "Altstetzsch 94",
    },
    {
      KunNr: 1197,
      KunName: "Brust",
      KunOrt: "Gruena bei Chemnitz",
      KunPLZ: "09224",
      KunStrasse: "Concordiastr. 151",
    },
    {
      KunNr: 1198,
      KunName: "Saathoff",
      KunOrt: "Grossschirma",
      KunPLZ: "09603",
      KunStrasse: "Luisenhofstieg 191",
    },
    {
      KunNr: 1199,
      KunName: "Erben",
      KunOrt: "Auerbach, Erzgebirge",
      KunPLZ: "09392",
      KunStrasse: "Fontanestrasse 109",
    },
    {
      KunNr: 1200,
      KunName: "Wanke",
      KunOrt: "Grossweitzschen",
      KunPLZ: "04720",
      KunStrasse: "Lia-Woehr-Platz 36",
    },
    {
      KunNr: 1201,
      KunName: "Pietzsch",
      KunOrt: "Johannstadt",
      KunPLZ: "01309",
      KunStrasse: "Buzzistrasse 199",
    },
    {
      KunNr: 1202,
      KunName: "Schnitzer",
      KunOrt: "Brandis bei Wurzen",
      KunPLZ: "04821",
      KunStrasse: "Obere Sterngasse 245",
    },
    {
      KunNr: 1203,
      KunName: "Dahlke",
      KunOrt: "Niederau bei Meissen",
      KunPLZ: "01689",
      KunStrasse: "Rat-Beil-Strasse 54",
    },
    {
      KunNr: 1204,
      KunName: "Kaltenbach",
      KunOrt: "Wachau bei Radeberg",
      KunPLZ: "01454",
      KunStrasse: "Hemmerleinstr. 79",
    },
    {
      KunNr: 1205,
      KunName: "Hochmuth",
      KunOrt: "Raschau-Markersbach",
      KunPLZ: "08352",
      KunStrasse: "Pflanzsteig 99",
    },
    {
      KunNr: 1206,
      KunName: "Moehle",
      KunOrt: "Dresden",
      KunPLZ: "01067",
      KunStrasse: "Berger Weg 167",
    },
    {
      KunNr: 1207,
      KunName: "Voegele",
      KunOrt: "Dorfhain",
      KunPLZ: "01738",
      KunStrasse: "Pfeiferstrasse 105",
    },
    {
      KunNr: 1208,
      KunName: "Gaida",
      KunOrt: "Uhyst, Spree",
      KunPLZ: "02999",
      KunStrasse: "Rauenthaler Weg 125",
    },
    {
      KunNr: 1209,
      KunName: "Jaeschke",
      KunOrt: "Liegau-Augustusbad",
      KunPLZ: "01454",
      KunStrasse: "Leisbergstrasse 42",
    },
    {
      KunNr: 1210,
      KunName: "Hoeller",
      KunOrt: "Liebschuetzberg",
      KunPLZ: "04758",
      KunStrasse: "Steinbeker Berg 240",
    },
    {
      KunNr: 1211,
      KunName: "Fellner",
      KunOrt: "Zwota",
      KunPLZ: "08267",
      KunStrasse: "Reitersfeldweg 190",
    },
    {
      KunNr: 1212,
      KunName: "Sutter",
      KunOrt: "Quolsdorf",
      KunPLZ: "02923",
      KunStrasse: "Gruenwinkel 12",
    },
    {
      KunNr: 1213,
      KunName: "Pfisterer",
      KunOrt: "Gorbitz",
      KunPLZ: "01217",
      KunStrasse: "Kruggasse 236",
    },
    {
      KunNr: 1214,
      KunName: "Wohlfarth",
      KunOrt: "Strassgraebchen",
      KunPLZ: "01936",
      KunStrasse: "Simsonstrasse 63",
    },
    {
      KunNr: 1215,
      KunName: "Kamm",
      KunOrt: "Penig",
      KunPLZ: "09322",
      KunStrasse: "Fetscherstrasse 237",
    },
    {
      KunNr: 1216,
      KunName: "Roediger",
      KunOrt: "Frohburg",
      KunPLZ: "04654",
      KunStrasse: "Wehlener Strasse 196",
    },
    {
      KunNr: 1217,
      KunName: "Ammon",
      KunOrt: "Stetzsch",
      KunPLZ: "01328",
      KunStrasse: "Gurkenallee 221",
    },
    {
      KunNr: 1218,
      KunName: "Strube",
      KunOrt: "Bad Schandau",
      KunPLZ: "01814",
      KunStrasse: "Laurinstrasse 234",
    },
    {
      KunNr: 1219,
      KunName: "Scheerer",
      KunOrt: "Bad Schlema",
      KunPLZ: "08301",
      KunStrasse: "Am Torfmoor 210",
    },
    {
      KunNr: 1220,
      KunName: "Ostermeier",
      KunOrt: "Zwickau",
      KunPLZ: "08062",
      KunStrasse: "Am Waeldchen 158",
    },
    {
      KunNr: 1221,
      KunName: "Rhein",
      KunOrt: "Spree",
      KunPLZ: "02923",
      KunStrasse: "Ottostr. 163",
    },
    {
      KunNr: 1222,
      KunName: "Seubert",
      KunOrt: "Ostritz",
      KunPLZ: "02899",
      KunStrasse: "Riedgrund 225",
    },
    {
      KunNr: 1223,
      KunName: "Hendricks",
      KunOrt: "Malter",
      KunPLZ: "01744",
      KunStrasse: "Friesstrasse 224",
    },
    {
      KunNr: 1224,
      KunName: "Franck",
      KunOrt: "Wiesen bei Zwickau",
      KunPLZ: "08134",
      KunStrasse: "Danziger Strasse 207",
    },
    {
      KunNr: 1225,
      KunName: "Sohn",
      KunOrt: "Elsterberg, Vogtland",
      KunPLZ: "07985",
      KunStrasse: "Kaltenbergen 195",
    },
    {
      KunNr: 1226,
      KunName: "Kloeckner",
      KunOrt: "Plauen, Vogtland",
      KunPLZ: "08525",
      KunStrasse: "Hoeblinggasse 119",
    },
    {
      KunNr: 1227,
      KunName: "Gruhn",
      KunOrt: "Leipzig",
      KunPLZ: "04277",
      KunStrasse: "Maternstr. 229",
    },
    {
      KunNr: 1228,
      KunName: "Schoenemann",
      KunOrt: "Ostritz",
      KunPLZ: "02899",
      KunStrasse: "Seehofstrasse 54",
    },
    {
      KunNr: 1229,
      KunName: "Kappes",
      KunOrt: "Burgstein bei Plauen",
      KunPLZ: "08538",
      KunStrasse: "Heunischstr. 233",
    },
    {
      KunNr: 1230,
      KunName: "Koelsch",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09112",
      KunStrasse: "Am Bahnhof 236",
    },
    {
      KunNr: 1231,
      KunName: "Kroell",
      KunOrt: "Priestewitz",
      KunPLZ: "01561",
      KunStrasse: "Cohausenstrasse 117",
    },
    {
      KunNr: 1232,
      KunName: "Hey",
      KunOrt: "Liebstadt",
      KunPLZ: "01825",
      KunStrasse: "Wilsdruffer Ring 214",
    },
    {
      KunNr: 1233,
      KunName: "Irmer",
      KunOrt: "Gorbitz",
      KunPLZ: "01217",
      KunStrasse: "Vilbeler Strasse 234",
    },
    {
      KunNr: 1234,
      KunName: "Stegmaier",
      KunOrt: "Heide",
      KunPLZ: "08340",
      KunStrasse: "Muehlenkampsweg 72",
    },
    {
      KunNr: 1235,
      KunName: "Selzer",
      KunOrt: "Pennrich",
      KunPLZ: "01156",
      KunStrasse: "An der Rennbahn 241",
    },
    {
      KunNr: 1236,
      KunName: "Dillmann",
      KunOrt: "Zschortau",
      KunPLZ: "04519",
      KunStrasse: "Alnpeckstrasse 221",
    },
    {
      KunNr: 1237,
      KunName: "Beetz",
      KunOrt: "Stetzsch",
      KunPLZ: "01189",
      KunStrasse: "Kurmarkstrasse 74",
    },
    {
      KunNr: 1238,
      KunName: "Kettler",
      KunOrt: "Gruenhainichen",
      KunPLZ: "09579",
      KunStrasse: "Am Langenzug 109",
    },
    {
      KunNr: 1239,
      KunName: "Adolf",
      KunOrt: "Borna bei Leipzig",
      KunPLZ: "04552",
      KunStrasse: "Steinbeker Weg 4",
    },
    {
      KunNr: 1240,
      KunName: "Eichholz",
      KunOrt: "Steinbach",
      KunPLZ: "01462",
      KunStrasse: "Riedhofweg 227",
    },
    {
      KunNr: 1241,
      KunName: "Niggemann",
      KunOrt: "Gorbitz",
      KunPLZ: "01465",
      KunStrasse: "Besselstrasse 216",
    },
    {
      KunNr: 1242,
      KunName: "Senft",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09116",
      KunStrasse: "Diebweg 227",
    },
    {
      KunNr: 1243,
      KunName: "Fellner",
      KunOrt: "Muegeln bei Oschatz",
      KunPLZ: "04769",
      KunStrasse: "Bernusstrasse 183",
    },
    {
      KunNr: 1244,
      KunName: "Moehle",
      KunOrt: "Zschorlau",
      KunPLZ: "08321",
      KunStrasse: "Braumannstrasse 206",
    },
    {
      KunNr: 1245,
      KunName: "Nienhaus",
      KunOrt: "Hochkirch",
      KunPLZ: "02627",
      KunStrasse: "Am Landigt 187",
    },
    {
      KunNr: 1246,
      KunName: "Mahnke",
      KunOrt: "Johannstadt",
      KunPLZ: "01159",
      KunStrasse: "Rohrbachstrasse 187",
    },
    {
      KunNr: 1247,
      KunName: "Seufert",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09125",
      KunStrasse: "Im Kammerdorf 237",
    },
    {
      KunNr: 1248,
      KunName: "Kaltenbach",
      KunOrt: "Friedrichstadt",
      KunPLZ: "01159",
      KunStrasse: "Obeliskgasse 172",
    },
    {
      KunNr: 1249,
      KunName: "Wassermann",
      KunOrt: "Lichtentanne",
      KunPLZ: "08115",
      KunStrasse: "Sachsenstrasse 126",
    },
    {
      KunNr: 1250,
      KunName: "Stevens",
      KunOrt: "Torgau",
      KunPLZ: "04860",
      KunStrasse: "Ohlendorffstrasse 86",
    },
    {
      KunNr: 1251,
      KunName: "Milz",
      KunOrt: "Johannstadt",
      KunPLZ: "01109",
      KunStrasse: "Vogelsanger Weg 145",
    },
    {
      KunNr: 1252,
      KunName: "Wittich",
      KunOrt: "Gorbitz",
      KunPLZ: "01277",
      KunStrasse: "Vogesenweg 154",
    },
    {
      KunNr: 1253,
      KunName: "Gaebler",
      KunOrt: "Eilenburg",
      KunPLZ: "04838",
      KunStrasse: "Gederner Strasse 67",
    },
    {
      KunNr: 1254,
      KunName: "Fleischhauer",
      KunOrt: "Kriebstein",
      KunPLZ: "09648",
      KunStrasse: "Schoenbacher Weg 105",
    },
    {
      KunNr: 1255,
      KunName: "Asmus",
      KunOrt: "Syrau",
      KunPLZ: "08548",
      KunStrasse: "Schillerplatz 186",
    },
    {
      KunNr: 1256,
      KunName: "Bangert",
      KunOrt: "Grossweitzschen",
      KunPLZ: "04720",
      KunStrasse: "Siedlungsstrasse 198",
    },
    {
      KunNr: 1257,
      KunName: "Effenberger",
      KunOrt: "Thallwitz",
      KunPLZ: "04808",
      KunStrasse: "Meurerweg 45",
    },
    {
      KunNr: 1258,
      KunName: "Gold",
      KunOrt: "Goerlitz, Neisse",
      KunPLZ: "02827",
      KunStrasse: "Alte Dorfstrasse 103",
    },
    {
      KunNr: 1259,
      KunName: "Dold",
      KunOrt: "Cunewalde",
      KunPLZ: "02733",
      KunStrasse: "Wartegaesschen 131",
    },
    {
      KunNr: 1260,
      KunName: "Weniger",
      KunOrt: "Steinigtwolmsdorf",
      KunPLZ: "01904",
      KunStrasse: "Chapeaurougeweg 136",
    },
    {
      KunNr: 1261,
      KunName: "Kracht",
      KunOrt: "Triebel / Vogtland",
      KunPLZ: "08606",
      KunStrasse: "Hanfftsweg 161",
    },
    {
      KunNr: 1262,
      KunName: "Weinberg",
      KunOrt: "Woellnau",
      KunPLZ: "04838",
      KunStrasse: "Bauerberg 69",
    },
    {
      KunNr: 1263,
      KunName: "Markgraf",
      KunOrt: "Eilenburg",
      KunPLZ: "04838",
      KunStrasse: "Gerberstrasse 210",
    },
    {
      KunNr: 1264,
      KunName: "Wehrmann",
      KunOrt: "Groeditz bei Riesa",
      KunPLZ: "01609",
      KunStrasse: "Rubensweg 241",
    },
    {
      KunNr: 1265,
      KunName: "Buechler",
      KunOrt: "Gorbitz",
      KunPLZ: "01097",
      KunStrasse: "Dielmannstrasse 54",
    },
    {
      KunNr: 1266,
      KunName: "Fellner",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09030",
      KunStrasse: "Melchiorstrasse 203",
    },
    {
      KunNr: 1267,
      KunName: "Pawlowski",
      KunOrt: "Gorbitz",
      KunPLZ: "01109",
      KunStrasse: "Am Bahndamm 67",
    },
    {
      KunNr: 1268,
      KunName: "Piontek",
      KunOrt: "Mochau bei Doebeln",
      KunPLZ: "04720",
      KunStrasse: "Altgomlitz 24",
    },
    {
      KunNr: 1269,
      KunName: "Doehler",
      KunOrt: "Elstertrebnitz",
      KunPLZ: "04523",
      KunStrasse: "Olbrichstrasse 196",
    },
    {
      KunNr: 1270,
      KunName: "Escher",
      KunOrt: "Gorbitz",
      KunPLZ: "01069",
      KunStrasse: "Kleemattstrasse 166",
    },
    {
      KunNr: 1271,
      KunName: "Waibel",
      KunOrt: "Limbach-Oberfrohna",
      KunPLZ: "09212",
      KunStrasse: "Masurenweg 66",
    },
    {
      KunNr: 1272,
      KunName: "Germann",
      KunOrt: "Liebschuetzberg",
      KunPLZ: "04758",
      KunStrasse: "Pflugspfad 235",
    },
    {
      KunNr: 1273,
      KunName: "Krupp",
      KunOrt: "Dresden",
      KunPLZ: "01324",
      KunStrasse: "Hutbergstrasse 91",
    },
    {
      KunNr: 1274,
      KunName: "Glock",
      KunOrt: "Gruenhainichen",
      KunPLZ: "09579",
      KunStrasse: "Pflugspfad 30",
    },
    {
      KunNr: 1275,
      KunName: "Siemer",
      KunOrt: "Marienau bei Zwickau",
      KunPLZ: "08132",
      KunStrasse: "Klein Herl 213",
    },
    {
      KunNr: 1276,
      KunName: "Bitzer",
      KunOrt: "Dresden",
      KunPLZ: "01108",
      KunStrasse: "Am Muehlenberg 176",
    },
    {
      KunNr: 1277,
      KunName: "Goerner",
      KunOrt: "Siebenlehn",
      KunPLZ: "09603",
      KunStrasse: "Fiefstuecken 235",
    },
    {
      KunNr: 1278,
      KunName: "Trommer",
      KunOrt: "Bad Schlema",
      KunPLZ: "08301",
      KunStrasse: "Woogstrasse 177",
    },
    {
      KunNr: 1279,
      KunName: "Plum",
      KunOrt: "Muegeln bei Oschatz",
      KunPLZ: "04769",
      KunStrasse: "Landseestrasse 42",
    },
    {
      KunNr: 1280,
      KunName: "Rump",
      KunOrt: "Stetzsch",
      KunPLZ: "01465",
      KunStrasse: "Langriedgasse 232",
    },
    {
      KunNr: 1281,
      KunName: "Piotrowski",
      KunOrt: "Lauter / Sachsen",
      KunPLZ: "08312",
      KunStrasse: "Hasselhorstweg 236",
    },
    {
      KunNr: 1282,
      KunName: "Peukert",
      KunOrt: "Niederwiesa",
      KunPLZ: "09577",
      KunStrasse: "Ratsstrasse 195",
    },
    {
      KunNr: 1283,
      KunName: "Mittelstaedt",
      KunOrt: "Stetzsch",
      KunPLZ: "01189",
      KunStrasse: "Kransberger Weg 157",
    },
    {
      KunNr: 1284,
      KunName: "Schlemmer",
      KunOrt: "Johannstadt",
      KunPLZ: "01219",
      KunStrasse: "Goerresstrasse 229",
    },
    {
      KunNr: 1285,
      KunName: "Klumpp",
      KunOrt: "Dresden",
      KunPLZ: "01159",
      KunStrasse: "Rathenaustrasse 152",
    },
    {
      KunNr: 1286,
      KunName: "Kaufhold",
      KunOrt: "Weisser Hirsch",
      KunPLZ: "01324",
      KunStrasse: "Markusplatz 208",
    },
    {
      KunNr: 1287,
      KunName: "Thum",
      KunOrt: "Gorbitz",
      KunPLZ: "01069",
      KunStrasse: "Schwanmanweg 26",
    },
    {
      KunNr: 1288,
      KunName: "Handke",
      KunOrt: "Erlbach-Kirchberg",
      KunPLZ: "09385",
      KunStrasse: "Mitterweg 133",
    },
    {
      KunNr: 1289,
      KunName: "Kuck",
      KunOrt: "Niesky",
      KunPLZ: "02906",
      KunStrasse: "Gruene Telle 60",
    },
    {
      KunNr: 1290,
      KunName: "Grosskopf",
      KunOrt: "Zoeblitz",
      KunPLZ: "09517",
      KunStrasse: "Telemannstrasse 162",
    },
    {
      KunNr: 1291,
      KunName: "Scheele",
      KunOrt: "Ossling",
      KunPLZ: "01920",
      KunStrasse: "Kirchberg 103",
    },
    {
      KunNr: 1292,
      KunName: "Scheffel",
      KunOrt: "Porschdorf",
      KunPLZ: "01814",
      KunStrasse: "Stemmanns Weg 32",
    },
    {
      KunNr: 1293,
      KunName: "Mehler",
      KunOrt: "Gorbitz",
      KunPLZ: "01239",
      KunStrasse: "Am Zaukenfeld 93",
    },
    {
      KunNr: 1294,
      KunName: "Stehr",
      KunOrt: "Gorbitz",
      KunPLZ: "01067",
      KunStrasse: "Oberndorfer Weg 225",
    },
    {
      KunNr: 1295,
      KunName: "Deininger",
      KunOrt: "Sohland an der Spree",
      KunPLZ: "02689",
      KunStrasse: "Am Badweg 23",
    },
    {
      KunNr: 1296,
      KunName: "Dieterle",
      KunOrt: "Gorbitz",
      KunPLZ: "01189",
      KunStrasse: "Korolenkostrasse 3",
    },
    {
      KunNr: 1297,
      KunName: "Schepers",
      KunOrt: "Taucha bei Leipzig",
      KunPLZ: "04425",
      KunStrasse: "Ruehlstrasse 152",
    },
    {
      KunNr: 1298,
      KunName: "Droege",
      KunOrt: "Zschepplin",
      KunPLZ: "04838",
      KunStrasse: "Falltorstrasse 123",
    },
    {
      KunNr: 1299,
      KunName: "Denecke",
      KunOrt: "Pegau",
      KunPLZ: "04523",
      KunStrasse: "Grempstrasse 68",
    },
    {
      KunNr: 1300,
      KunName: "Nordmann",
      KunOrt: "Kohren-Sahlis",
      KunPLZ: "04655",
      KunStrasse: "Airportring 242",
    },
    {
      KunNr: 1301,
      KunName: "Vaupel",
      KunOrt: "Elstra",
      KunPLZ: "01920",
      KunStrasse: "Geigerstrasse 74",
    },
    {
      KunNr: 1302,
      KunName: "Griebel",
      KunOrt: "Grosslehna",
      KunPLZ: "04420",
      KunStrasse: "Dammgasse 130",
    },
    {
      KunNr: 1303,
      KunName: "Weck",
      KunOrt: "Rammenau",
      KunPLZ: "01877",
      KunStrasse: "Arensweg 59",
    },
    {
      KunNr: 1304,
      KunName: "Heinecke",
      KunOrt: "Hartha bei Doebeln",
      KunPLZ: "04746",
      KunStrasse: "Oberer Kreutberg 113",
    },
    {
      KunNr: 1305,
      KunName: "Karger",
      KunOrt: "Schoeneck / Vogtland",
      KunPLZ: "08261",
      KunStrasse: "Bruckertshof 7",
    },
    {
      KunNr: 1306,
      KunName: "Eitel",
      KunOrt: "Leipzig",
      KunPLZ: "04279",
      KunStrasse: "Gaertnerstrasse 227",
    },
    {
      KunNr: 1307,
      KunName: "Hackbarth",
      KunOrt: "Frohburg",
      KunPLZ: "04654",
      KunStrasse: "Teichrosenweg 242",
    },
    {
      KunNr: 1308,
      KunName: "Stang",
      KunOrt: "Muegeln bei Oschatz",
      KunPLZ: "04769",
      KunStrasse: "Schlossstr. 109",
    },
    {
      KunNr: 1309,
      KunName: "Gilles",
      KunOrt: "Zoellmen",
      KunPLZ: "01462",
      KunStrasse: "Loeherstrasse 139",
    },
    {
      KunNr: 1310,
      KunName: "Blankenburg",
      KunOrt: "Grossnaundorf",
      KunPLZ: "01936",
      KunStrasse: "Zum Lehmfeld 82",
    },
    {
      KunNr: 1311,
      KunName: "Fick",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09111",
      KunStrasse: "Wiesengrund 178",
    },
    {
      KunNr: 1312,
      KunName: "Klostermann",
      KunOrt: "Markkleeberg",
      KunPLZ: "04416",
      KunStrasse: "Schreberweg 83",
    },
    {
      KunNr: 1313,
      KunName: "Sohn",
      KunOrt: "Mildenau",
      KunPLZ: "09456",
      KunStrasse: "Neunkircher Weg 144",
    },
    {
      KunNr: 1314,
      KunName: "Graupner",
      KunOrt: "Koenigsbrueck",
      KunPLZ: "01936",
      KunStrasse: "Kruppstrasse 160",
    },
    {
      KunNr: 1315,
      KunName: "Kirschbaum",
      KunOrt: "Ketzerbachtal",
      KunPLZ: "01623",
      KunStrasse: "Suedhoehe 149",
    },
    {
      KunNr: 1316,
      KunName: "Zach",
      KunOrt: "Stoermthal",
      KunPLZ: "04463",
      KunStrasse: "Bundenweg 80",
    },
    {
      KunNr: 1317,
      KunName: "Wittek",
      KunOrt: "Wilsdruff",
      KunPLZ: "01723",
      KunStrasse: "Grauener Weg 13",
    },
    {
      KunNr: 1318,
      KunName: "Koppe",
      KunOrt: "Elstertrebnitz",
      KunPLZ: "04523",
      KunStrasse: "Reussstr. 191",
    },
    {
      KunNr: 1319,
      KunName: "Kamps",
      KunOrt: "Ostritz",
      KunPLZ: "02899",
      KunStrasse: "Dinglingerstrasse 85",
    },
    {
      KunNr: 1320,
      KunName: "Thom",
      KunOrt: "Geising",
      KunPLZ: "01778",
      KunStrasse: "Konopkastrasse 87",
    },
    {
      KunNr: 1321,
      KunName: "Stang",
      KunOrt: "Schoenau bei Zwickau",
      KunPLZ: "08134",
      KunStrasse: "Brueckenweg 152",
    },
    {
      KunNr: 1322,
      KunName: "Pongratz",
      KunOrt: "Reinhardtsgrimma",
      KunPLZ: "01768",
      KunStrasse: "Boehmertstrasse 153",
    },
    {
      KunNr: 1323,
      KunName: "Hirschfeld",
      KunOrt: "Bennewitz bei Wurzen",
      KunPLZ: "04828",
      KunStrasse: "Niederauer Platz 36",
    },
    {
      KunNr: 1324,
      KunName: "Schulten",
      KunOrt: "Steinbach",
      KunPLZ: "01462",
      KunStrasse: "Satzriedgasse 245",
    },
    {
      KunNr: 1325,
      KunName: "Woehrle",
      KunOrt: "Kreba-Neudorf",
      KunPLZ: "02906",
      KunStrasse: "Hainer Weg 244",
    },
    {
      KunNr: 1326,
      KunName: "Lex",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "02633",
      KunStrasse: "Battenberger Weg 146",
    },
    {
      KunNr: 1327,
      KunName: "Hansmann",
      KunOrt: "Dresden",
      KunPLZ: "01259",
      KunStrasse: "Gereuthstr. 178",
    },
    {
      KunNr: 1328,
      KunName: "Edel",
      KunOrt: "Leippen",
      KunPLZ: "01665",
      KunStrasse: "Querstrasse 66",
    },
    {
      KunNr: 1329,
      KunName: "Klingenberg",
      KunOrt: "Niederwiesa",
      KunPLZ: "09577",
      KunStrasse: "Elkenbachstrasse 193",
    },
    {
      KunNr: 1330,
      KunName: "Angermann",
      KunOrt: "Gelenau / Erzgebirge",
      KunPLZ: "09423",
      KunStrasse: "Reclamstrasse 130",
    },
    {
      KunNr: 1331,
      KunName: "Schlemmer",
      KunOrt: "Dresden",
      KunPLZ: "01169",
      KunStrasse: "Holzhauerweg 190",
    },
    {
      KunNr: 1332,
      KunName: "Heppner",
      KunOrt: "Rosenbach bei Loebau",
      KunPLZ: "02708",
      KunStrasse: "Severusstrasse 177",
    },
    {
      KunNr: 1333,
      KunName: "Storz",
      KunOrt: "Muegeln bei Oschatz",
      KunPLZ: "04769",
      KunStrasse: "Muenzgasse 153",
    },
    {
      KunNr: 1334,
      KunName: "Behrmann",
      KunOrt: "Dresden",
      KunPLZ: "01069",
      KunStrasse: "Schlossstrasse 188",
    },
    {
      KunNr: 1335,
      KunName: "Ortner",
      KunOrt: "Waldsteinberg",
      KunPLZ: "04821",
      KunStrasse: "Am Dorfplatz 194",
    },
    {
      KunNr: 1336,
      KunName: "Tempel",
      KunOrt: "Zwota",
      KunPLZ: "08267",
      KunStrasse: "Am Spritzenhaus 92",
    },
    {
      KunNr: 1337,
      KunName: "Burk",
      KunOrt: "Schkeuditz",
      KunPLZ: "04435",
      KunStrasse: "Waldwiesenstr. 139",
    },
    {
      KunNr: 1338,
      KunName: "Orlowski",
      KunOrt: "Bad Schandau",
      KunPLZ: "01814",
      KunStrasse: "Kaendlerstrasse 230",
    },
    {
      KunNr: 1339,
      KunName: "Breidenbach",
      KunOrt: "Stetzsch",
      KunPLZ: "01067",
      KunStrasse: "Luebecker Strasse 72",
    },
    {
      KunNr: 1340,
      KunName: "Ploetz",
      KunOrt: "Altfranken",
      KunPLZ: "01156",
      KunStrasse: "Elkenbachstrasse 156",
    },
    {
      KunNr: 1341,
      KunName: "Hoelzel",
      KunOrt: "Waldhufen",
      KunPLZ: "02906",
      KunStrasse: "Schraegkamp 210",
    },
    {
      KunNr: 1342,
      KunName: "Loibl",
      KunOrt: "Freiberg",
      KunPLZ: "08626",
      KunStrasse: "Lannerstrasse 92",
    },
    {
      KunNr: 1343,
      KunName: "Felber",
      KunOrt: "Johannstadt",
      KunPLZ: "01237",
      KunStrasse: "Lukasstrasse 244",
    },
    {
      KunNr: 1344,
      KunName: "Brueckmann",
      KunOrt: "Floeha",
      KunPLZ: "09557",
      KunStrasse: "Doebraer Strasse 158",
    },
    {
      KunNr: 1345,
      KunName: "Schneck",
      KunOrt: "Leubnitz bei Plauen",
      KunPLZ: "08412",
      KunStrasse: "Am Hollergraben 243",
    },
    {
      KunNr: 1346,
      KunName: "Juettner",
      KunOrt: "Gersdorf",
      KunPLZ: "04746",
      KunStrasse: "Gasse 203",
    },
    {
      KunNr: 1347,
      KunName: "Markmann",
      KunOrt: "Wittichenau",
      KunPLZ: "02997",
      KunStrasse: "Fischergasse 114",
    },
    {
      KunNr: 1348,
      KunName: "Berberich",
      KunOrt: "Wermsdorf",
      KunPLZ: "04779",
      KunStrasse: "Buger Hauptstr. 172",
    },
    {
      KunNr: 1349,
      KunName: "Kullmann",
      KunOrt: "Johannstadt",
      KunPLZ: "01109",
      KunStrasse: "Moenchhofstrasse 52",
    },
    {
      KunNr: 1350,
      KunName: "Felber",
      KunOrt: "Grossbothen",
      KunPLZ: "04668",
      KunStrasse: "Severusstrasse 39",
    },
    {
      KunNr: 1351,
      KunName: "Alber",
      KunOrt: "Gorbitz-Sued",
      KunPLZ: "01169",
      KunStrasse: "Altnausslitz 17",
    },
    {
      KunNr: 1352,
      KunName: "Salewski",
      KunOrt: "Wyhratal",
      KunPLZ: "04552",
      KunStrasse: "Scheibenbergweg 78",
    },
    {
      KunNr: 1353,
      KunName: "Wiest",
      KunOrt: "Stetzsch",
      KunPLZ: "01069",
      KunStrasse: "Hoepers Kamp 49",
    },
    {
      KunNr: 1354,
      KunName: "Velten",
      KunOrt: "Floeha",
      KunPLZ: "09557",
      KunStrasse: "Ignaz Nuss-Weg 103",
    },
    {
      KunNr: 1355,
      KunName: "Knittel",
      KunOrt: "Zwickau",
      KunPLZ: "08056",
      KunStrasse: "LennÃ©strasse 223",
    },
    {
      KunNr: 1356,
      KunName: "Mandel",
      KunOrt: "Leippen",
      KunPLZ: "01665",
      KunStrasse: "Zschaukegraben 9",
    },
    {
      KunNr: 1357,
      KunName: "Mast",
      KunOrt: "Kleindalzig",
      KunPLZ: "04442",
      KunStrasse: "Rugestrasse 114",
    },
    {
      KunNr: 1358,
      KunName: "Heidt",
      KunOrt: "Johannstadt",
      KunPLZ: "01127",
      KunStrasse: "Blumenstr. 112",
    },
    {
      KunNr: 1359,
      KunName: "Lanz",
      KunOrt: "Bad Brambach",
      KunPLZ: "08648",
      KunStrasse: "Am Marienbad 14",
    },
    {
      KunNr: 1360,
      KunName: "Emde",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09113",
      KunStrasse: "Blagnac-Bruecke 243",
    },
    {
      KunNr: 1361,
      KunName: "Kienle",
      KunOrt: "Stetzsch",
      KunPLZ: "01259",
      KunStrasse: "Ilextwiete 30",
    },
    {
      KunNr: 1362,
      KunName: "Michler",
      KunOrt: "Stetzsch",
      KunPLZ: "01129",
      KunStrasse: "Tiberiusstrasse 182",
    },
    {
      KunNr: 1363,
      KunName: "Rick",
      KunOrt: "Dresden",
      KunPLZ: "01067",
      KunStrasse: "Blanchardstrasse 110",
    },
    {
      KunNr: 1364,
      KunName: "Holm",
      KunOrt: "Burkau",
      KunPLZ: "01906",
      KunStrasse: "Zinggstrasse 185",
    },
    {
      KunNr: 1365,
      KunName: "Wittek",
      KunOrt: "Goerlitz, Neisse",
      KunPLZ: "02828",
      KunStrasse: "Spliedtring 107",
    },
    {
      KunNr: 1366,
      KunName: "Doehler",
      KunOrt: "Waldheim, Sachsen",
      KunPLZ: "04736",
      KunStrasse: "Flughafenstrasse 12",
    },
    {
      KunNr: 1367,
      KunName: "Mueck",
      KunOrt: "Ehrenfriedersdorf",
      KunPLZ: "09427",
      KunStrasse: "Kemmerstr. 189",
    },
    {
      KunNr: 1368,
      KunName: "Angermann",
      KunOrt: "Schoepstal",
      KunPLZ: "02829",
      KunStrasse: "Moenchsleite 87",
    },
    {
      KunNr: 1369,
      KunName: "Juengling",
      KunOrt: "Muehlental",
      KunPLZ: "08626",
      KunStrasse: "Gucksbergweg 244",
    },
    {
      KunNr: 1370,
      KunName: "Spitz",
      KunOrt: "Rackwitz",
      KunPLZ: "04519",
      KunStrasse: "Huswertstrasse 225",
    },
    {
      KunNr: 1371,
      KunName: "Wurster",
      KunOrt: "Bennewitz bei Wurzen",
      KunPLZ: "04828",
      KunStrasse: "Laschoberstrasse 78",
    },
    {
      KunNr: 1372,
      KunName: "Retzlaff",
      KunOrt: "Stein",
      KunPLZ: "08118",
      KunStrasse: "Stegstrasse 87",
    },
    {
      KunNr: 1373,
      KunName: "Seelig",
      KunOrt: "Tharandt",
      KunPLZ: "01737",
      KunStrasse: "Steinigtwiesenweg 32",
    },
    {
      KunNr: 1374,
      KunName: "Edel",
      KunOrt: "Dresden",
      KunPLZ: "01462",
      KunStrasse: "Blochmatt 64",
    },
    {
      KunNr: 1375,
      KunName: "Tappe",
      KunOrt: "Bernsbach",
      KunPLZ: "08315",
      KunStrasse: "Laubegaster Weg 182",
    },
    {
      KunNr: 1376,
      KunName: "Steigerwald",
      KunOrt: "Rochlitz",
      KunPLZ: "09306",
      KunStrasse: "Klarastrasse 28",
    },
    {
      KunNr: 1377,
      KunName: "Kuntze",
      KunOrt: "Mittweida",
      KunPLZ: "09648",
      KunStrasse: "Wormser Strasse 213",
    },
    {
      KunNr: 1378,
      KunName: "Fritzsch",
      KunOrt: "Zschocken",
      KunPLZ: "08118",
      KunStrasse: "Adickesallee 2",
    },
    {
      KunNr: 1379,
      KunName: "Brueckmann",
      KunOrt: "Neustadt / Vogtland",
      KunPLZ: "08223",
      KunStrasse: "Stoeckelstrasse 66",
    },
    {
      KunNr: 1380,
      KunName: "Gaul",
      KunOrt: "Lohmen, Sachsen",
      KunPLZ: "01847",
      KunStrasse: "Lugbank 33",
    },
    {
      KunNr: 1381,
      KunName: "Blohm",
      KunOrt: "Oderwitz",
      KunPLZ: "02791",
      KunStrasse: "Lersnerstrasse 236",
    },
    {
      KunNr: 1382,
      KunName: "Kimmel",
      KunOrt: "Rohrbach",
      KunPLZ: "01920",
      KunStrasse: "Lippeltstrasse 69",
    },
    {
      KunNr: 1383,
      KunName: "Ostermeier",
      KunOrt: "Gruenbach, Vogtland",
      KunPLZ: "08223",
      KunStrasse: "Am Schreiberbach 203",
    },
    {
      KunNr: 1384,
      KunName: "Franck",
      KunOrt: "Pennrich",
      KunPLZ: "01156",
      KunStrasse: "Markusstr. 244",
    },
    {
      KunNr: 1385,
      KunName: "Grosse",
      KunOrt: "Leipzig",
      KunPLZ: "04129",
      KunStrasse: "Karlshagener Weg 25",
    },
    {
      KunNr: 1386,
      KunName: "Schiessl",
      KunOrt: "Bernsbach",
      KunPLZ: "08315",
      KunStrasse: "Fuhrenkamp 206",
    },
    {
      KunNr: 1387,
      KunName: "Nehring",
      KunOrt: "Niederstriegis",
      KunPLZ: "04741",
      KunStrasse: "Am Hopfenfeld 157",
    },
    {
      KunNr: 1388,
      KunName: "Kienle",
      KunOrt: "Oederan",
      KunPLZ: "09569",
      KunStrasse: "Howisch 32",
    },
    {
      KunNr: 1389,
      KunName: "Matheis",
      KunOrt: "Grossolbersdorf",
      KunPLZ: "09432",
      KunStrasse: "Hebebrandstrasse 129",
    },
    {
      KunNr: 1390,
      KunName: "Sohn",
      KunOrt: "Grimma",
      KunPLZ: "04668",
      KunStrasse: "Muehlensteig 180",
    },
    {
      KunNr: 1391,
      KunName: "Ruck",
      KunOrt: "Bad Muskau",
      KunPLZ: "02953",
      KunStrasse: "Birkenallee 126",
    },
    {
      KunNr: 1392,
      KunName: "Amend",
      KunOrt: "Stetzsch",
      KunPLZ: "01259",
      KunStrasse: "Hellbrookstrasse 79",
    },
    {
      KunNr: 1393,
      KunName: "Heppner",
      KunOrt: "Cossebaude",
      KunPLZ: "01462",
      KunStrasse: "Kamelienweg 168",
    },
    {
      KunNr: 1394,
      KunName: "Till",
      KunOrt: "Riesa",
      KunPLZ: "01587",
      KunStrasse: "Erlengrund 163",
    },
    {
      KunNr: 1395,
      KunName: "Pietschmann",
      KunOrt: "Mochau bei Doebeln",
      KunPLZ: "04720",
      KunStrasse: "Am Ende 125",
    },
    {
      KunNr: 1396,
      KunName: "Reinsch",
      KunOrt: "Plauen, Vogtland",
      KunPLZ: "08525",
      KunStrasse: "Adalbertstrasse 192",
    },
    {
      KunNr: 1397,
      KunName: "Breitenbach",
      KunOrt: "Kurort Oybin",
      KunPLZ: "02797",
      KunStrasse: "Schwarmweg 138",
    },
    {
      KunNr: 1398,
      KunName: "Zitzmann",
      KunOrt: "Gorbitz",
      KunPLZ: "01478",
      KunStrasse: "Am Brauhaus 156",
    },
    {
      KunNr: 1399,
      KunName: "Mauch",
      KunOrt: "Grosstreben-Zwethau",
      KunPLZ: "04886",
      KunStrasse: "Handelsstrasse 127",
    },
    {
      KunNr: 1400,
      KunName: "Mittelstaedt",
      KunOrt: "Pulsnitz",
      KunPLZ: "01896",
      KunStrasse: "Roseggerstrasse 8",
    },
    {
      KunNr: 1401,
      KunName: "Klostermann",
      KunOrt: "Dresden",
      KunPLZ: "01309",
      KunStrasse: "Waldsportpfad 177",
    },
    {
      KunNr: 1402,
      KunName: "Sebastian",
      KunOrt: "Gruena bei Chemnitz",
      KunPLZ: "09224",
      KunStrasse: "Dielmannstrasse 73",
    },
    {
      KunNr: 1403,
      KunName: "Clauss",
      KunOrt: "Glashuette, Sachsen",
      KunPLZ: "01768",
      KunStrasse: "Buchsbaumstrasse 245",
    },
    {
      KunNr: 1404,
      KunName: "Fels",
      KunOrt: "Friedrichstadt",
      KunPLZ: "01157",
      KunStrasse: "Gaertnerweg 198",
    },
    {
      KunNr: 1405,
      KunName: "Hildenbrand",
      KunOrt: "Hoyerswerda",
      KunPLZ: "02977",
      KunStrasse: "Franklinstrasse 202",
    },
    {
      KunNr: 1406,
      KunName: "Runkel",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "02633",
      KunStrasse: "Spitalgasse 53",
    },
    {
      KunNr: 1407,
      KunName: "Schmoll",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "02692",
      KunStrasse: "Georginenweg 26",
    },
    {
      KunNr: 1408,
      KunName: "Reisch",
      KunOrt: "Stetzsch",
      KunPLZ: "01237",
      KunStrasse: "Vollmarstrasse 6",
    },
    {
      KunNr: 1409,
      KunName: "Pitz",
      KunOrt: "Mehltheuer, Vogtland",
      KunPLZ: "08539",
      KunStrasse: "Fersenfeldtsweg 177",
    },
    {
      KunNr: 1410,
      KunName: "Moog",
      KunOrt: "Wyhratal",
      KunPLZ: "04552",
      KunStrasse: "Tornaer Ring 186",
    },
    {
      KunNr: 1411,
      KunName: "Diefenbach",
      KunOrt: "Zabeltitz",
      KunPLZ: "01561",
      KunStrasse: "Michael Mayr-Gasse 8",
    },
    {
      KunNr: 1412,
      KunName: "Juenemann",
      KunOrt: "Stetzsch",
      KunPLZ: "01279",
      KunStrasse: "Wunschring 51",
    },
    {
      KunNr: 1413,
      KunName: "Brennecke",
      KunOrt: "Nepperwitz",
      KunPLZ: "04828",
      KunStrasse: "Am Pfarrlehn 140",
    },
    {
      KunNr: 1414,
      KunName: "Limbach",
      KunOrt: "Leipzig",
      KunPLZ: "04178",
      KunStrasse: "Tornaer Ring 116",
    },
    {
      KunNr: 1415,
      KunName: "Michler",
      KunOrt: "Kirschau",
      KunPLZ: "02681",
      KunStrasse: "Kampener Stieg 222",
    },
    {
      KunNr: 1416,
      KunName: "Buechel",
      KunOrt: "Dresden",
      KunPLZ: "01189",
      KunStrasse: "Bluecherweg 210",
    },
    {
      KunNr: 1417,
      KunName: "Strube",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09120",
      KunStrasse: "Sudetenstr. 151",
    },
    {
      KunNr: 1418,
      KunName: "Storz",
      KunOrt: "Sankt Egidien",
      KunPLZ: "09356",
      KunStrasse: "Kirchnerstrasse 175",
    },
    {
      KunNr: 1419,
      KunName: "Scheele",
      KunOrt: "Zeithain",
      KunPLZ: "01619",
      KunStrasse: "Wachwitzblick 34",
    },
    {
      KunNr: 1420,
      KunName: "Strube",
      KunOrt: "Gorbitz",
      KunPLZ: "01219",
      KunStrasse: "Kurparkstrasse 210",
    },
    {
      KunNr: 1421,
      KunName: "Christian",
      KunOrt: "Grosstreben-Zwethau",
      KunPLZ: "04886",
      KunStrasse: "Barfussweg 5",
    },
    {
      KunNr: 1422,
      KunName: "Stief",
      KunOrt: "Elterlein",
      KunPLZ: "09481",
      KunStrasse: "Am Dorfende 14",
    },
    {
      KunNr: 1423,
      KunName: "Loth",
      KunOrt: "Zschortau",
      KunPLZ: "04519",
      KunStrasse: "Hahnbergweg 205",
    },
    {
      KunNr: 1424,
      KunName: "Schnitzer",
      KunOrt: "Pausa / Vogtland",
      KunPLZ: "07952",
      KunStrasse: "Herriotstrasse 75",
    },
    {
      KunNr: 1425,
      KunName: "Fuehrer",
      KunOrt: "Wuelknitz bei Riesa",
      KunPLZ: "01609",
      KunStrasse: "Seebachstrasse 127",
    },
    {
      KunNr: 1426,
      KunName: "Unruh",
      KunOrt: "Hundshuebel",
      KunPLZ: "08318",
      KunStrasse: "Gadelsdorfer Weg 39",
    },
    {
      KunNr: 1427,
      KunName: "Streich",
      KunOrt: "Dresden",
      KunPLZ: "01156",
      KunStrasse: "Am Viverdamm 231",
    },
    {
      KunNr: 1428,
      KunName: "Vaupel",
      KunOrt: "Gorbitz",
      KunPLZ: "01277",
      KunStrasse: "Junghansstrasse 6",
    },
    {
      KunNr: 1429,
      KunName: "Zeiler",
      KunOrt: "Elsterheide",
      KunPLZ: "02979",
      KunStrasse: "NicodÃ©strasse 138",
    },
    {
      KunNr: 1430,
      KunName: "Weigert",
      KunOrt: "Theuma",
      KunPLZ: "08541",
      KunStrasse: "Ochsenangerstr. 165",
    },
    {
      KunNr: 1431,
      KunName: "Dobler",
      KunOrt: "Imnitz",
      KunPLZ: "04442",
      KunStrasse: "Rote Bruecke 220",
    },
    {
      KunNr: 1432,
      KunName: "Franzke",
      KunOrt: "Syrau",
      KunPLZ: "08548",
      KunStrasse: "Lange Allee 96",
    },
    {
      KunNr: 1433,
      KunName: "Reinsch",
      KunOrt: "Grossharthau",
      KunPLZ: "01909",
      KunStrasse: "Graben 163",
    },
    {
      KunNr: 1434,
      KunName: "Dorner",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "01877",
      KunStrasse: "Mirabellenweg 216",
    },
    {
      KunNr: 1435,
      KunName: "Gessner",
      KunOrt: "Mausitz",
      KunPLZ: "04442",
      KunStrasse: "Panoramaweg 168",
    },
    {
      KunNr: 1436,
      KunName: "Lembke",
      KunOrt: "Oberschoena",
      KunPLZ: "09600",
      KunStrasse: "Nordstrasse 122",
    },
    {
      KunNr: 1437,
      KunName: "Helfrich",
      KunOrt: "Sehmatal",
      KunPLZ: "09465",
      KunStrasse: "Stammannstrasse 17",
    },
    {
      KunNr: 1438,
      KunName: "Hotz",
      KunOrt: "Neuensalz",
      KunPLZ: "08541",
      KunStrasse: "Bauhofstrasse 25",
    },
    {
      KunNr: 1439,
      KunName: "Edel",
      KunOrt: "Niedercunnersdorf",
      KunPLZ: "02708",
      KunStrasse: "Tichystrasse 227",
    },
    {
      KunNr: 1440,
      KunName: "Pausch",
      KunOrt: "Mulda / Sachsen",
      KunPLZ: "09619",
      KunStrasse: "Muenterweg 39",
    },
    {
      KunNr: 1441,
      KunName: "Bacher",
      KunOrt: "Falkenau, Sachsen",
      KunPLZ: "09569",
      KunStrasse: "Bickenbacher Weg 105",
    },
    {
      KunNr: 1442,
      KunName: "Mueck",
      KunOrt: "Stein",
      KunPLZ: "08118",
      KunStrasse: "Am Weissiger Bach 1",
    },
    {
      KunNr: 1443,
      KunName: "Selle",
      KunOrt: "Schoenteichen",
      KunPLZ: "01920",
      KunStrasse: "Wartenau 94",
    },
    {
      KunNr: 1444,
      KunName: "Rohrbach",
      KunOrt: "Zschaitz-Ottewig",
      KunPLZ: "04720",
      KunStrasse: "Wiesenteich 60",
    },
    {
      KunNr: 1445,
      KunName: "Heinzel",
      KunOrt: "Kittlitz bei Loebau",
      KunPLZ: "02708",
      KunStrasse: "Stiehlerstrasse 237",
    },
    {
      KunNr: 1446,
      KunName: "Staub",
      KunOrt: "Eulowitz",
      KunPLZ: "02692",
      KunStrasse: "Holzgrund 106",
    },
    {
      KunNr: 1447,
      KunName: "Wassermann",
      KunOrt: "Bretnig-Hauswalde",
      KunPLZ: "01900",
      KunStrasse: "Schadowstrasse 89",
    },
    {
      KunNr: 1448,
      KunName: "Groll",
      KunOrt: "Grosspoesna",
      KunPLZ: "04463",
      KunStrasse: "Muehlsdorfer Weg 58",
    },
    {
      KunNr: 1449,
      KunName: "Haeuser",
      KunOrt: "Hochkirch",
      KunPLZ: "02627",
      KunStrasse: "Rotenbrueckenweg 80",
    },
    {
      KunNr: 1450,
      KunName: "Jahns",
      KunOrt: "Altfranken",
      KunPLZ: "01156",
      KunStrasse: "Barlachstrasse 91",
    },
    {
      KunNr: 1451,
      KunName: "Nass",
      KunOrt: "Brand-Erbisdorf",
      KunPLZ: "09618",
      KunStrasse: "Elli-Lucht-Park 180",
    },
    {
      KunNr: 1452,
      KunName: "Andreas",
      KunOrt: "Ockerwitz",
      KunPLZ: "01462",
      KunStrasse: "Rattlergasse 44",
    },
    {
      KunNr: 1453,
      KunName: "Prill",
      KunOrt: "Cavertitz",
      KunPLZ: "04758",
      KunStrasse: "Max-Bromme-Steig 28",
    },
    {
      KunNr: 1454,
      KunName: "Niehoff",
      KunOrt: "Oberlungwitz",
      KunPLZ: "09353",
      KunStrasse: "Koerberstrasse 186",
    },
    {
      KunNr: 1455,
      KunName: "Fels",
      KunOrt: "Johannstadt",
      KunPLZ: "01328",
      KunStrasse: "Pietzschstrasse 190",
    },
    {
      KunNr: 1456,
      KunName: "Dannenberg",
      KunOrt: "Haselbach",
      KunPLZ: "09526",
      KunStrasse: "Schanzstrasse 220",
    },
    {
      KunNr: 1457,
      KunName: "Grossmann",
      KunOrt: "Karcha",
      KunPLZ: "01683",
      KunStrasse: "Hohle Gasse 53",
    },
    {
      KunNr: 1458,
      KunName: "Matheis",
      KunOrt: "Pennrich",
      KunPLZ: "01156",
      KunStrasse: "Quosdorfstrasse 47",
    },
    {
      KunNr: 1459,
      KunName: "Graeber",
      KunOrt: "Unkersdorf",
      KunPLZ: "01462",
      KunStrasse: "Stadtdeich 230",
    },
    {
      KunNr: 1460,
      KunName: "Goldbach",
      KunOrt: "Lohmen, Sachsen",
      KunPLZ: "01847",
      KunStrasse: "Keulenbergstrasse 31",
    },
    {
      KunNr: 1461,
      KunName: "Dannenberg",
      KunOrt: "Chemnitz, Sachsen",
      KunPLZ: "09112",
      KunStrasse: "Am Burghof 139",
    },
    {
      KunNr: 1462,
      KunName: "Vollrath",
      KunOrt: "Johannstadt",
      KunPLZ: "01237",
      KunStrasse: "Diemelstrasse 91",
    },
    {
      KunNr: 1463,
      KunName: "Nolting",
      KunOrt: "Ottendorf-Okrilla",
      KunPLZ: "01458",
      KunStrasse: "Ruppendorfer Weg 163",
    },
    {
      KunNr: 1464,
      KunName: "Brennecke",
      KunOrt: "Colditz",
      KunPLZ: "04680",
      KunStrasse: "Cheruskerweg 134",
    },
    {
      KunNr: 1465,
      KunName: "Piel",
      KunOrt: "Struppen",
      KunPLZ: "01796",
      KunStrasse: "Haarweg 236",
    },
    {
      KunNr: 1466,
      KunName: "Wenger",
      KunOrt: "Machern bei Wurzen",
      KunPLZ: "04827",
      KunStrasse: "Poeppelmannstrasse 1",
    },
    {
      KunNr: 1467,
      KunName: "Goerlich",
      KunOrt: "Stetzsch",
      KunPLZ: "01277",
      KunStrasse: "Tocklergasse 224",
    },
    {
      KunNr: 1468,
      KunName: "Bonn",
      KunOrt: "Kamenz",
      KunPLZ: "01917",
      KunStrasse: "Lia-Woehr-Platz 171",
    },
    {
      KunNr: 1469,
      KunName: "Rebmann",
      KunOrt: "Taura bei Burgstaedt",
      KunPLZ: "09249",
      KunStrasse: "Seilergasse 147",
    },
    {
      KunNr: 1470,
      KunName: "Haider",
      KunOrt: "Innere Altstadt",
      KunPLZ: "01067",
      KunStrasse: "Willemerstrasse 91",
    },
    {
      KunNr: 1471,
      KunName: "Jasper",
      KunOrt: "Bernsbach",
      KunPLZ: "08315",
      KunStrasse: "Olenhoffweg 226",
    },
    {
      KunNr: 1472,
      KunName: "Sternberg",
      KunOrt: "Otterwisch",
      KunPLZ: "04668",
      KunStrasse: "Burgsdorffstrasse 59",
    },
    {
      KunNr: 1473,
      KunName: "Sauermann",
      KunOrt: "Niederwartha",
      KunPLZ: "01462",
      KunStrasse: "Faehrmannweg 23",
    },
    {
      KunNr: 1474,
      KunName: "Liese",
      KunOrt: "Riesa",
      KunPLZ: "01589",
      KunStrasse: "Billufer 185",
    },
    {
      KunNr: 1475,
      KunName: "Eichmann",
      KunOrt: "Nausslitz",
      KunPLZ: "01159",
      KunStrasse: "Heerstrasse 144",
    },
    {
      KunNr: 1476,
      KunName: "Nordmann",
      KunOrt: "Hainichen, Sachsen",
      KunPLZ: "09661",
      KunStrasse: "Suedhang 125",
    },
    {
      KunNr: 1477,
      KunName: "Hochmuth",
      KunOrt: "Muehlau bei Chemnitz",
      KunPLZ: "09241",
      KunStrasse: "Melisseweg 223",
    },
    {
      KunNr: 1478,
      KunName: "Effenberger",
      KunOrt: "Gorbitz",
      KunPLZ: "01189",
      KunStrasse: "Borgesch 125",
    },
    {
      KunNr: 1479,
      KunName: "Dieterle",
      KunOrt: "Reinhardtsgrimma",
      KunPLZ: "01768",
      KunStrasse: "Brunnenstrasse 154",
    },
    {
      KunNr: 1480,
      KunName: "Zell",
      KunOrt: "Niederfrohna",
      KunPLZ: "09243",
      KunStrasse: "Am Weissen Turm 186",
    },
    {
      KunNr: 1481,
      KunName: "Hackbarth",
      KunOrt: "Grosshartmannsdorf",
      KunPLZ: "09618",
      KunStrasse: "Casimirstrasse 59",
    },
    {
      KunNr: 1482,
      KunName: "Wiemer",
      KunOrt: "Obergurig",
      KunPLZ: "02692",
      KunStrasse: "Im Gutacker 131",
    },
    {
      KunNr: 1483,
      KunName: "Lichtenberg",
      KunOrt: "Eulatal",
      KunPLZ: "04651",
      KunStrasse: "Pohrsdorfer Weg 210",
    },
    {
      KunNr: 1484,
      KunName: "Hengst",
      KunOrt: "Zschortau",
      KunPLZ: "04519",
      KunStrasse: "Ermelstrasse 92",
    },
    {
      KunNr: 1485,
      KunName: "Strehl",
      KunOrt: "Thallwitz",
      KunPLZ: "04808",
      KunStrasse: "Kellerberg 25",
    },
    {
      KunNr: 1486,
      KunName: "Ferber",
      KunOrt: "Friedrichstadt",
      KunPLZ: "01157",
      KunStrasse: "Spiegelweg 76",
    },
    {
      KunNr: 1487,
      KunName: "Weinzierl",
      KunOrt: "Plauen, Vogtland",
      KunPLZ: "08523",
      KunStrasse: "Flurstrasse 87",
    },
    {
      KunNr: 1488,
      KunName: "Kahlert",
      KunOrt: "Stetzsch",
      KunPLZ: "01279",
      KunStrasse: "Knorrstrasse 181",
    },
    {
      KunNr: 1489,
      KunName: "Voegele",
      KunOrt: "Kreissa",
      KunPLZ: "01623",
      KunStrasse: "Bahnhaeuser 187",
    },
    {
      KunNr: 1490,
      KunName: "Liebe",
      KunOrt: "Niederwuerschnitz",
      KunPLZ: "09399",
      KunStrasse: "Friebelstrasse 99",
    },
    {
      KunNr: 1491,
      KunName: "Guettler",
      KunOrt: "Neukirch / Lausitz",
      KunPLZ: "01904",
      KunStrasse: "Aronstr. 34",
    },
    {
      KunNr: 1492,
      KunName: "Schnoor",
      KunOrt: "Johannstadt",
      KunPLZ: "01187",
      KunStrasse: "Am Gleise 214",
    },
    {
      KunNr: 1493,
      KunName: "Israel",
      KunOrt: "Johannstadt",
      KunPLZ: "01129",
      KunStrasse: "Herchenhainer Weg 76",
    },
    {
      KunNr: 1494,
      KunName: "Gessner",
      KunOrt: "Leipzig",
      KunPLZ: "04107",
      KunStrasse: "Brauereiweg 147",
    },
    {
      KunNr: 1495,
      KunName: "Sand",
      KunOrt: "Bad Muskau",
      KunPLZ: "02953",
      KunStrasse: "Amselgrund 231",
    },
    {
      KunNr: 1496,
      KunName: "Kaluza",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "02633",
      KunStrasse: "Pommernweg 178",
    },
    {
      KunNr: 1497,
      KunName: "Pfitzner",
      KunOrt: "Kaendler",
      KunPLZ: "09247",
      KunStrasse: "Am Dorngraben 51",
    },
    {
      KunNr: 1498,
      KunName: "Weiner",
      KunOrt: "Johannstadt",
      KunPLZ: "01328",
      KunStrasse: "Gleinaer Strasse 159",
    },
    {
      KunNr: 1499,
      KunName: "Schlesinger",
      KunOrt: "Doberschau-Gaussig",
      KunPLZ: "01877",
      KunStrasse: "Lehmkuhlenweg 132",
    },
    {
      KunNr: 1500,
      KunName: "Mehler",
      KunOrt: "Siebenlehn",
      KunPLZ: "09634",
      KunStrasse: "Buenaustrasse 96",
    },
  ];
});

const onPage = async (event: any) => {
  page.value = event.first;
  await fetchCustomers();
};

const onFilter = async (event: any) => {
  const { filters } = event;
  Object.keys(filters).forEach((x) => {
    if (filters[x].constraints[0].value) {
      filterOptions.value[x] = {
        value: filters[x].constraints[0].value,
        matchMode: filters[x].constraints[0].matchMode,
      };
    } else {
      filterOptions.value.hasOwnProperty(x)
        ? delete filterOptions.value[x]
        : null;
    }
  });
  await fetchCustomers();
};

const onSort = async (event: any) => {
  const { sortField, sortOrder } = event;
  if (sortField) {
    sortOptions.value[sortField] = sortOrder === 1 ? "asc" : "desc";
  } else {
    sortOptions.value = {};
  }
  await fetchCustomers();
};

const fetchCustomers = async () => {
  isLoading.value = true;
  await customerService.list(
    sortOptions.value,
    filterOptions.value,
    page.value,
    rows.value
  );
  isLoading.value = false;
};

const onProductSelect = (event: any) => {
  emit("selectRow", event.data);
};
</script>

<style scoped></style>
